# Generated by Django 3.0.8 on 2020-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('github', models.URLField()),
                ('thumbnail', models.ImageField(upload_to=None)),
            ],
        ),
    ]
